// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Token    string `form:"token"`
	UserID   string `form:"userID"`
	Platform string `form:"platform"`
}
type Response struct {
	Uid     string
	ErrMsg  string
	Success bool
}
